# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('subject', models.CharField(max_length=150)),
                ('code', models.TextField()),
                ('plain_code', models.TextField()),
                ('reply_address', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='QueuedMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_to', models.EmailField(max_length=254)),
                ('mail_from', models.EmailField(blank=True, max_length=254, null=True)),
                ('send_after', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('context_vars', models.TextField(default=b'[]')),
                ('status', models.CharField(choices=[(b'queued', 'The mail is waiting in the queue'), (b'send', 'The mail has been send successfully'), (b'error', 'There was an error when sending this email')], default=b'queued', max_length=10)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailzer.MailTemplate')),
            ],
        ),
    ]
